title: Tabular Copula
description: Tabular Synthetic Generation using Gaussian Copula
theme: just-the-docs

url: https://biomeddar.github.io/copula-tabular/

aux_links:
  Template Repository: https://github.com/BiomedDAR/copula-tabular

footer_content: "Copyright &copy; 2023 BiomedDAR. Distributed by an <a href=\"https://github.com/BiomedDAR/copula-tabular/blob/main/LICENSE\">MIT license.</a>"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html